"""bookkit.render — turn the model into Markdown, JSONL, digests and payloads.

Three output shapes, three consumers:

* **Markdown** — a human (or an LLM) reads the chapter; page anchors live in
  HTML comments so the file stays clean but stays traceable.
* **JSONL** — retrieval-friendly chunks with page/section/role metadata and
  the OCR flags attached, ready for embedding or grep.
* **Digest** — a *context-window-friendly* map of the book: per page, what is
  there, what is broken, what needs eyes.  This is what an agent reads first.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Iterable, Optional, Sequence

from . import __version__, structure

if TYPE_CHECKING:  # pragma: no cover
    from .core import Book, Page, Paragraph
    from .quality import Flag, Report

MATHISH = re.compile(
    r"(?:\d+\s*[+\-*/×÷=]\s*\d+|\\frac|\\sum|\\int|\^\s*\d|[a-z]\s*=\s*[-0-9]|"
    r"\b(?:mod|gcd|lcm)\b|∑|∫|≤|≥|≠)", re.I)
OPERATORS = re.compile(r"[=+\-*/×÷^<>√∑∫≤≥≠]")
WORDISH = re.compile(r"[A-Za-z]{3,}")


def is_mathish(text: str) -> bool:
    """Heuristic: a short line with operators and few words is probably maths."""
    if len(text) > 200:
        return False
    ops = OPERATORS.findall(text)
    words = WORDISH.findall(text)
    digits = sum(ch.isdigit() for ch in text)
    return (len(ops) >= 2 and digits >= 1 and len(words) <= 4) or \
        (bool(MATHISH.search(text)) and len(words) <= 3)


def _fence(text: str) -> str:
    """Wrap probable maths so a reader/LLM does not 'fix' it as prose."""
    return "`" + text.strip() + "`" if is_mathish(text) else text


# --------------------------------------------------------------------------
# markdown
# --------------------------------------------------------------------------


@dataclass
class MarkdownOptions:
    title: Any = None                 # override the book title
    page_breaks: bool = True          # HTML comment markers per page
    include_flags: bool = True        # inline warnings for suspicious lines
    include_outline: bool = True      # table of contents at the top
    drop_furniture: bool = True       # running heads/folios already removed
    heading_prefix: str = ""
    max_heading_level: int = 4


def _md_escape(text: str) -> str:
    return text.replace("<", "&lt;").replace(">", "&gt;")


def to_markdown(book: "Book", report: Optional["Report"] = None,
                opts: MarkdownOptions | None = None) -> str:
    opts = opts or MarkdownOptions()
    out: list[str] = []
    info = book.info()
    title = opts.title or info.get("title") or _guess_title(book) or book.path.stem
    out.append(f"# {title}")
    out.append("")
    src = book.path.name
    bits = [f"pages: {info['pages']}", f"source: `{src}`"]
    if info.get("author"):
        bits.append(f"author: {info['author']}")
    if info.get("scanned_pages"):
        bits.append("scanned/OCR text layer")
    out.append(" ".join(f"*{b}*" for b in bits))
    out.append("")

    if opts.include_outline:
        entries = structure.outline(book)
        if entries:
            out.append("## Outline")
            out.append("")
            for e in entries:
                if e.level > opts.max_heading_level:
                    continue
                pad = "  " * max(0, e.level - 1)
                out.append(f"{pad}- {e.title}  *(p{e.page})*")
            out.append("")

    flag_index: dict[int, list["Flag"]] = {}
    if report is not None and opts.include_flags:
        for f in report.flags:
            if f.line is not None:
                flag_index.setdefault(f.page, []).append(f)

    # problems/exercises are re-flowed from their merged form, so a statement
    # split across lines by the scanner is rendered as the single unit it is
    merged: dict[int, list[structure.Item]] = {}
    for it in structure.items(book):
        merged.setdefault(id(it.paragraphs[0]), []).append(it)
    consumed: set[int] = set()

    for page in book.pages:
        if opts.page_breaks:
            out.append(f"<!-- bookkit:page={page.number} -->")
        page_flags = flag_index.get(page.number, [])
        for par in page.paragraphs:
            items_here = merged.get(id(par))
            if items_here:
                it = items_here[0]
                for member in it.paragraphs:
                    consumed.add(id(member))
                out.extend(_render_item(it, page_flags, opts))
                continue
            if id(par) in consumed:
                continue
            out.extend(_render_paragraph(par, page_flags, opts))
        out.append("")

    out.append("")
    out.append(f"<!-- generated by bookkit {__version__} -->")
    return "\n".join(_compact_blank(out))


def _guess_title(book: "Book") -> str:
    entries = structure.outline(book)
    for e in entries:
        if e.level == 0:
            return e.title.strip()
    for e in entries:
        if e.level == 1:
            return e.title.strip()
    return ""


def _render_item(it: structure.Item, flags: Sequence["Flag"],
                 opts: MarkdownOptions) -> list[str]:
    """Render a merged problem/exercise/solution as one Markdown block."""
    from .core import Paragraph  # local: keeps the module import-light

    lines_n = it.line_numbers()
    my_flags = [f for f in flags if f.line in lines_n]
    warn = ""
    if my_flags and opts.include_flags:
        codes = ", ".join(sorted({f.code for f in my_flags}))
        warn = f" <!-- ⚠ OCR {codes} @p{it.page} -->"

    text = it.text.strip()
    if it.kind == "problem":
        return [f"> **{text}**{warn}", ""]
    if it.kind == "solution":
        return [f"**Solution** — {_fence(text)}{warn}", ""]
    if it.kind == "exercise":
        num = it.number or ""
        body = text
        if num and body.startswith(num):
            body = body[len(num):].lstrip("★* ").strip()
        star = "★ " if it.star else ""
        suffix = ""
        if it.hints:
            suffix = f"  *(hints: {', '.join(it.hints)})*"
        return [f"- **{star}{num}** {_fence(body)}{suffix}{warn}"]
    if it.kind == "example":
        return [f"**Example** — {_fence(text)}{warn}", ""]
    return [f"> {_fence(text)}{warn}", ""]


def _render_paragraph(par: "Paragraph", flags: Sequence["Flag"],
                      opts: MarkdownOptions) -> list[str]:
    text = par.text.strip()
    if not text:
        return []
    lines: list[str] = []
    tag = f"p{par.page_no}"
    my_flags = [f for f in flags if f.text and f.text.strip() == text]
    warn = ""
    if my_flags:
        codes = ", ".join(sorted({f"{f.code}" for f in my_flags}))
        warn = f" <!-- ⚠ OCR {codes} @{tag} -->"

    if par.role == structure.ROLE_HEADING:
        level = par.level if par.level is not None else 2
        level = max(1, min(level + 1, 6))  # bookkit level 0 -> "#"
        if par.level == 0:
            level = 1
        lines.append(f"{'#' * level} {text}")
        lines.append("")
    elif par.role == structure.ROLE_PROBLEM:
        lines.append(f"> **{text}**{warn}")
        lines.append("")
    elif par.role == structure.ROLE_SOLUTION:
        lines.append(f"**Solution** — {_fence(text)}{warn}")
        lines.append("")
    elif par.role == structure.ROLE_EXERCISE:
        body = text
        num = par.number or ""
        if num and body.startswith(num):
            body = body[len(num):].lstrip("* ").strip()
        star = "★ " if par.attrs.get("star") else ""
        lines.append(f"- **{star}{num}** {_fence(body)}{warn}")
    elif par.role == structure.ROLE_LABEL:
        lines.append(f"**{text}**{warn}")
        lines.append("")
    elif par.role == structure.ROLE_EXAMPLE:
        lines.append(f"**Example** — {_fence(text)}{warn}")
        lines.append("")
    elif par.role == structure.ROLE_THEOREM:
        lines.append(f"> {_fence(text)}{warn}")
        lines.append("")
    elif par.role == structure.ROLE_NOISE:
        return []
    else:
        body = _fence(text)
        if par.attrs.get("in_box"):
            lines.append(f"> {body}{warn}")
        else:
            lines.append(f"{body}{warn}")
        lines.append("")
    return lines


def _compact_blank(lines: Sequence[str]) -> list[str]:
    out: list[str] = []
    for ln in lines:
        if ln == "" and out and out[-1] == "":
            continue
        out.append(ln)
    return out


# --------------------------------------------------------------------------
# chunks
# --------------------------------------------------------------------------


@dataclass
class Chunk:
    id: str
    text: str
    page: int
    end_page: int
    role: str
    section: Optional[str] = None
    section_number: Optional[str] = None
    number: Optional[str] = None
    bbox: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0)
    lines: list[int] = field(default_factory=list)
    flags: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            "id": self.id,
            "page": self.page,
            "end_page": self.end_page,
            "role": self.role,
            "text": self.text,
            "lines": self.lines,
            "bbox": [round(v, 1) for v in self.bbox],
        }
        if self.section:
            d["section"] = self.section
        if self.section_number:
            d["section_number"] = self.section_number
        if self.number:
            d["number"] = self.number
        if self.flags:
            d["flags"] = self.flags
        return d


def chunks(book: "Book", report: Optional["Report"] = None,
           merge_items: bool = True) -> list[Chunk]:
    """Paragraph-level chunks, with problems/exercises merged into one chunk."""
    items = structure.items(book) if merge_items else []
    # paragraph identity -> the item it belongs to
    item_text: dict[int, Any] = {}
    for it in items:
        for p in it.paragraphs:
            item_text[id(p)] = it
    emitted: set[int] = set()

    flags_by_page: dict[int, list["Flag"]] = {}
    if report is not None:
        for f in report.flags:
            flags_by_page.setdefault(f.page, []).append(f)

    out: list[Chunk] = []
    for page in book.pages:
        for par in page.paragraphs:
            if par.role == structure.ROLE_NOISE:
                continue
            it = item_text.get(id(par))
            if it is not None and merge_items:
                if id(it) in emitted:
                    continue  # only the first paragraph emits the merged chunk
                emitted.add(id(it))
                number = it.number or str(len(out))
                cid = f"p{it.page}:{it.kind}:{number}"
                flags = [f.code for f in flags_by_page.get(it.page, [])
                         if f.line in set(it.line_numbers())]
                out.append(Chunk(
                    id=cid, text=it.text, page=it.page, end_page=it.end_page,
                    role=it.kind, section=it.section, section_number=it.section_number,
                    number=it.number, bbox=it.bbox, lines=it.line_numbers(),
                    flags=sorted(set(flags)),
                ))
                continue
            flags = [f.code for f in flags_by_page.get(page.number, []) if f.line in par.line_numbers()]
            out.append(Chunk(
                id=f"p{page.number}:{par.role}:{par.line_numbers()[0] if par.lines else 0}",
                text=par.text, page=page.number, end_page=page.number, role=par.role,
                bbox=par.bbox, lines=par.line_numbers(), flags=sorted(set(flags)),
            ))
    return out


def chunks_jsonl(book: "Book", report: Optional["Report"] = None) -> str:
    return "\n".join(json.dumps(c.to_dict(), ensure_ascii=False) for c in chunks(book, report)) + "\n"


# --------------------------------------------------------------------------
# digest
# --------------------------------------------------------------------------


def digest(book: "Book", report: Optional["Report"] = None, per_page: int = 220,
           include_clean: bool = False) -> dict[str, Any]:
    """A compact map of the book for a limited context window."""
    info = book.info()
    items = structure.items(book)
    by_page: dict[int, list[structure.Item]] = {}
    for it in items:
        by_page.setdefault(it.page, []).append(it)
    flags_by_page: dict[int, list["Flag"]] = {}
    if report is not None:
        for f in report.flags:
            flags_by_page.setdefault(f.page, []).append(f)

    sections = structure.sections(book)
    pages: list[dict[str, Any]] = []
    for page in book.pages:
        page_flags = flags_by_page.get(page.number, [])
        pr = None
        if report is not None:
            pr = next((p for p in report.pages if p.number == page.number), None)
        verdict = pr.verdict if pr else "unknown"
        if verdict == "clean" and not include_clean and not page_flags and not by_page.get(page.number):
            continue
        # the *most specific* section wins: "1.2 Counting Lists of Numbers",
        # not the enclosing "CHAPTER 1"
        covering = [s for s in sections
                    if s["page"] <= page.number <= s.get("end_page", s["page"])]
        sec = max(covering, key=lambda s: s["level"]) if covering else None
        pages.append({
            "page": page.number,
            "verdict": verdict,
            "score": pr.score if pr else 0.0,
            "section": sec["title"] if sec else None,
            "chars": page.chars,
            "items": [
                {"id": it.id, "tag": it.tag, "in_box": it.in_box,
                 "duplicate_of": it.duplicate_of, "hints": it.hints}
                for it in by_page.get(page.number, [])
            ],
            "flags": sorted({f.code for f in page_flags}),
            "preview": (page.text[:per_page] + "…") if len(page.text) > per_page else page.text,
        })
    return {
        "bookkit": __version__,
        "path": info["path"],
        "pages": info["pages"],
        "title": info.get("title") or _guess_title(book),
        "reading_size": report.reading_size if report else None,
        "outline": [e.to_dict() for e in structure.outline(book)][:240],
        "sections": sections,
        "item_counts": _count_kinds(items),
        "ocr": report.summary() if report else None,
        "digest_pages": pages,
    }


def _count_kinds(items: Sequence[structure.Item]) -> dict[str, int]:
    out: dict[str, int] = {}
    for it in items:
        out[it.kind] = out.get(it.kind, 0) + 1
    return out


def digest_text(book: "Book", report: Optional["Report"] = None, per_page: int = 200) -> str:
    d = digest(book, report, per_page=per_page)
    out = [
        f"# {d['title'] or d['path']}",
        f"pages={d['pages']} items={d['item_counts']}",
        "",
        "## outline",
    ]
    for e in d["outline"]:
        out.append(f"{'  ' * max(0, e['level'] - 1)}- [{e['level']}] {e['title']} (p{e['page']})")
    if d["ocr"]:
        o = d["ocr"]
        out.append("")
        out.append(f"## ocr: score={o['score']} verdicts={o['verdicts']} flags={o['flag_counts']}")
    out.append("")
    out.append("## pages (non-clean only)")
    for p in d["digest_pages"]:
        head = f"p{p['page']} [{p['verdict']}]"
        if p["section"]:
            head += f" §{p['section']}"
        if p["items"]:
            head += " items:" + ",".join(i["id"] for i in p["items"])
        if p["flags"]:
            head += " ⚠" + ",".join(p["flags"])
        out.append(head)
        out.append("   " + p["preview"].replace("\n", " ")[:per_page])
    return "\n".join(out)


# --------------------------------------------------------------------------
# web payload
# --------------------------------------------------------------------------


def payload(book: "Book", report: Optional["Report"] = None,
            page: Optional[int] = None, dpi: int = 150) -> dict[str, Any]:
    """Everything a UI needs: book info, outline, items, flags, page text."""
    info = book.info()
    pages = book.pages if page is None else [book.page(page)]
    flags_by_page: dict[int, list["Flag"]] = {}
    if report is not None:
        for f in report.flags:
            flags_by_page.setdefault(f.page, []).append(f)
    return {
        "bookkit": __version__,
        "info": info,
        "pages": [
            {
                "number": p.number,
                "width": p.width,
                "height": p.height,
                "chars": p.chars,
                "raster": p.raster,
                "raster_px": list(p.raster_px),
                "header": p.header,
                "folio": p.folio,
                "paragraphs": [par.to_dict() for par in p.paragraphs],
                "lines": [
                    {"i": l.index, "text": l.text, "bbox": [round(v, 1) for v in l.bbox],
                     "junk": l.junk}
                    for l in p.lines
                ],
                "flags": [f.to_dict() for f in flags_by_page.get(p.number, [])],
            }
            for p in pages
        ],
        "outline": [e.to_dict() for e in structure.outline(book)],
        "sections": structure.sections(book),
        "items": [it.to_dict(text=False) for it in structure.items(book)],
        "ocr": report.summary() if report else None,
        "render_dpi": dpi,
    }
